language: python
python:
    - "2.7"
    - "3.5"
    - "3.6"
install:
    - pip install pytest-cov
    - pip install codecov
    - pip install -r requirements.txt
script:
    - py.test --cov=./
after_success:
    - codecov --token=fe9862ba-9505-43b5-af77-b82817268852
